export const scannedItems = {
  ADD_NEW_ITEMS: "ADD_NEW_ITEMS",
  REMOVE_ITEM: "REMOVE_ITEM",
  SHOW_APP_MODAL: "SHOW_APP_MODAL",
  CHECKOUT_ITEMS: "CHECKOUT_ITEMS",
  CODE_DOES_NOT_EXIST: "CODE_DOES_NOT_EXIST",
  SHOW_DELETE_ITEM_MODAL: "SHOW_DELETE_ITEM_MODAL"
};
